baseURL = "https://mrnordstrom.com"
languageCode = "en-us"
title = "The NORD Notes"
theme = "nordix"
copyright = "Creative Commons Attribution-NoDerivatives 4.0 International License"

[author]
    name = "Daniel Nordstrom"
    email = "d@mrnordstrom.com"
[markup]
  [markup.highlight]
    guessSyntax = true
    hl_inline = false
    lineNos = true
    lineNumbersInTable = false
    noHl = false
    style = 'murphy'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

