baseURL: https://mrnordstrom.com
languageCode: en-us
title: The NORD Notes
theme: nordix
copyright: CC-BY-ND 4.0 International
newContentEditor: vim
titleCaseStyle: Chicago
taxonomies:
  tag: tags
permalinks:
  notes: ":slug"
author:
  name: Daniel Nordstrom
  email: d@mrnordstrom.com
markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
    style: murphy
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true

